### ISSUE TITLE
[BUG] removing concentration condition fails

### ISSUE THREAD

**Issue by DarKDinDoN** [death-save/combat-utility-belt#622]
**Describe the bug**
Exact same bug as this closed issue: https://github.com/death-save/combat-utility-belt/issues/591

![image](https://user-images.githubusercontent.com/1687854/141691677-e5314c13-f78e-4fcd-884d-9ef855eca158.png)

The only difference with the mentioned issue is that the error appears randomly.
Sometimes it works just fine, and sometimes I can't remove the concentration status and need to press F5.

I can confirm the following:
- Only CUB is installed
- Concentration name in CUBPuter and condition lab is the same (triple checked that)

Notes:
- With more modules activated, the more likely this issue will happen
- Makes me think of some kind of racing issue (or slowness issue due to other modules activated)
- Still, I was able to reproduce that only with CUB installed. I needed a lot more testing to reproduce (like clicking a spell and toggling the concentration status effect **at least for 1 minutes**, sometimes refreshing the instance)

Concentration configuration:
![image](https://user-images.githubusercontent.com/1687854/141692387-e2cc0259-e94d-4fc6-8fbf-5eea48b7e373.png)

**Environment Info (please complete the following information)**:
- Foundry Version: 0.8.9
- Game System / Version: dnd5e 1.5.3
- CUB Version: 1.7.2
- Browser: Chrome
- OS: Windows 10

**Comment by Fridan99** [comment]
The same happens to me.... i think is something with an interaction with DAE effects and CUB concentration..... 
In the spells that has no DAE effects, works fine.... 

![](https://cdn.discordapp.com/attachments/722566083499786352/910182299801370684/1.jpg)

![](https://cdn.discordapp.com/attachments/722566083499786352/910182892070633524/1.jpg)

![](https://cdn.discordapp.com/attachments/722566083499786352/910183990743412777/1.jpg)

![](https://cdn.discordapp.com/attachments/722566083499786352/910183993117405184/2.jpg)

![](https://cdn.discordapp.com/attachments/722566083499786352/910183994765770772/3.jpg)

When I cast the spell (Divine favor with DAE effects), 2 concentration symbols appear on the actor... when I click on apply effect in the chat, one disappears and the symbol of the DAE effect is superimposed.
I could try to remove the CUB concentration and do it by Midi to see if the bug persists.

I manage the concentration with midi-qol instead of CUB, and the problem was gone.
