### ISSUE TITLE
Concentration error

### ISSUE THREAD

**Issue by ParryDuckKill** [death-save/combat-utility-belt#646]
I'm using CUB for D&D 5e on the Foundry. I'm also using the Tidy5e Sheet module. When I cast a concentration spell, the concentration symbol is added on the line in my spellbook next to the spell itself. Not just on the effects tab, but right next to the spell too. 

![Combat Utility Belt, Unicorn](https://user-images.githubusercontent.com/97116401/148092741-58614248-943e-4edc-8582-038a308f24a3.jpg)

When I end the concentration effect, that symbol remains on the line next to the spell title ad infinitum. Nothing I've tried short of deleting the spell from the NPC's sheet will get rid of that symbol. This is occurring with all modules disabled except Tidy5e and CUB.

I'm using:
 - Foundry Version: 0.8.9
 - Game System / Version: 1.5.3
 - CUB Version: 1.7.3
 - Browser: Chrome
 - OS: Windows 10

**Comment by eclarke12** [comment]
What happens if you refresh the page after the spell ends? 0.8.9 had a bug that could cause ghost things like that.

**Comment by eclarke12** [comment]
@ParryDuckKill I should also note this issue of having ghost data should be resolved when you update to Foundry v9 (it was a core bug as far as I know)

**Comment by cs96and** [comment]
I see this issue too.  It happens when the "Automatically End Concentration" option is **not** set.  When you manually remove concentration (either via the token HUD, or via the Effects tab of the character sheet, then the concentration marker remains next to the spell.

The issue is here...

https://github.com/death-save/combat-utility-belt/blob/3b08a691b81bad4c0b2207ad03835b499820abe0/modules/concentrator.js#L220-L225

The `autoEndConcentration` check should be removed here, and it should always remove concentration if the user manually removed the active effect.

**Comment by eclarke12** [comment]
> I see this issue too. It happens when the "Automatically End Concentration" option is **not** set. When you manually remove concentration (either via the token HUD, or via the Effects tab of the character sheet, then the concentration marker remains next to the spell.
> 
> The issue is here...
> 
> https://github.com/death-save/combat-utility-belt/blob/3b08a691b81bad4c0b2207ad03835b499820abe0/modules/concentrator.js#L220-L225
> 
> The `autoEndConcentration` check should be removed here, and it should always remove concentration if the user manually removed the active effect.

This is a separate issue I think to the one originally reported, but I appreciate the info and will assess in the next patch.
