### ISSUE TITLE
dnd5e conditions have broken compendium links

### ISSUE THREAD

**Issue by spirritus** [death-save/combat-utility-belt#706]
**Describe the bug**
Conditions outputted to chat have broken compendium links

**To Reproduce**
1. Enable conditions output in chat. 
2. apply condition
3. observe broken condition compendium link in chat

**Expected behavior**
The condition link is clickable and displays the condition text.

**Environment Info (please complete the following information):**
 - Foundry Version: 10.248
 - Game System / Version: dnd 2.0.2
 - CUB Version 1.10.1
 - Browser Firefox
 - OS Debian 11

**Comment by Timecrash** [comment]
I'm seeing this too. The only condition seemingly unaffected is Concentrating.

An example image:
![image](https://user-images.githubusercontent.com/15052506/189248974-e095c833-3563-4393-a7c8-676929191008.png)

**Comment by Jayderose** [comment]
I get the sane broken links. If I try to re-add the link via drag and drop, is does not work.
I tested by creating a new condition and trying to drag/drop from the compendium, journal, etc. and no joy.

**Comment by eclarke12** [comment]
This is due to the changes to the `dnd5e.rules` compendium (to use Journal Entry Pages). If you are using the `System - Default` mapping this will be fixed with CUB v1.10.2, however if you have a custom mapping, you will need to update the references. The new reference Ids are listed below.

|Condition|New Reference Id|
|-|-|
|Blinded|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.0b8N4FymGGfbZGpJ]{Blinded}|
|Charmed|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.zZaEBrKkr66OWJvD]{Charmed}|
|Deafened|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.6G8JSjhn701cBITY]{Deafened}|
|Exhaustion|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.cspWveykstnu3Zcv]{Exhaustion}|
|Frightened|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.oreoyaFKnvZCrgij]{Frightened}|
|Grappled|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.gYDAhd02ryUmtwZn]{Grappled}|
|Incapacitated|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.TpkZgLfxCmSndmpb]{Incapacitated}|
|Invisible|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.3UU5GCTVeRDbZy9u]{Invisible}|
|Paralyzed|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.xnSV5hLJIMaTABXP]{Paralyzed}|
|Petrified|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.xaNDaW6NwQTgHSmi]{Petrified}|
|Poisoned|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.lq3TRI6ZlED8ABMx]{Poisoned}|
|Prone|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.y0TkcdyoZlOTmAFT]{Prone}|
|Restrained|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.cSVcyZyNe2iG1fIc]{Restrained}|
|Stunned|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.ZyZMUwA2rboh4ObS]{Stunned}|
|Unconscious|@UUID[Compendium.dnd5e.rules.w7eitkpD7QQTB6j0.JournalEntryPage.UWw13ISmMxDzmwbd]{Unconscious}|

**Comment by Fragmenri** [comment]
@eclarke12 
I'm sorry to reopen a closed case, but i'm trying to learn how to use the Condition lab with the v10.0.3.
It took me a while to understand what's happening but I finally managed to get that :

`System-Default` is still broken
![image](https://user-images.githubusercontent.com/117613562/200215885-796536c0-4b50-4ad4-92b8-efdc19b41a8d.png)

Good news is if I import "dnd5e.json", it comes back. (but that's not what you announced on your previous comment.
![image](https://user-images.githubusercontent.com/117613562/200216046-aed94249-d9f1-4ff7-a45e-0acdc42d0d13.png)

Bad news is importing "dnd5e-extended.json" goes wrong again. And icons from the spell related condition don't work either
![image](https://user-images.githubusercontent.com/117613562/200216201-8a73d8b8-95d0-4d4b-ba5f-fb1456ecd5c2.png)

Did I do something bad somewhere ?
