### ISSUE TITLE
Conditions are rapidly toggled when activated via Token Action HUD

### ISSUE THREAD

**Issue by nickelpro** [death-save/combat-utility-belt#713]
**Describe the bug**
Unsure who this bug belongs to.

When a CUB condition is click from the HUD provided by [Token Action HUD](https://github.com/Drental/fvtt-tokenactionhud), the condition rapidly toggles twice. CUB conditions can still be added and removed normally via active effects and the default Foundry token HUD.

**To Reproduce**
1. Install Token Action HUD and Combat Utility Belt
2. Create token
3. Apply CUB condition with Token Action HUD

**Expected behavior**
Condition state changes as expected

**Screenshots**

https://user-images.githubusercontent.com/1032552/190841368-06599e31-ebb5-4a74-bda8-5ff691f4c075.mp4

**Environment Info (please complete the following information):**
 - Foundry Version: v10.285
 - Game System / Version: dnd52 2.02
 - CUB Version: 1.10.1
 - Browser: chrome
 - OS: Arch Linux

**Additional context**
If this isn't CUB's bug I'll happily open against Token Action HUD, but I figured since TAH works with vanilla conditions I would start here.

**Comment by gris-x** [comment]
+1 

This has been happening since the past few days only, it worked fine before, and I switched to V10 when it released.
This is happening even with only Token HUD and CUP module. no other ones.

This only occurs for custom condition created from the condition lab (file atttached)


[cub-dnd5e-condition-map.txt](https://github.com/death-save/combat-utility-belt/files/9595226/cub-dnd5e-condition-map.txt)

**Comment by eclarke12** [comment]
This is appears to be fixed with CUB v1.10.2 (releasing soon), Foundry v10.287, TAH 3.011
